---
version: "2"

run:
  timeout: 30s
  tests: false

linters:
  disable-all: true
  enable:
    # core correctness
    - govet
    - staticcheck
    - errcheck
    - errorlint
    - err113

    # code quality & maintainability
    - gocritic
    - goconst

  settings:
    gocritic:
      disable-all: false
      enabled-checks:
        - hugeParam
        - rangeValCopy
      settings:
        hugeParam:
          sizeThreshold: 80
        rangeValCopy:
          sizeThreshold: 512
    goconst:
      min-len: 2
      min-occurrences: 2
